import pytest
from unittest.mock import patch, MagicMock
import json
from server.services.text_generation_service import TextGenerationService
from server.services.translation_service import TranslationService
from server.models import ReadingText, ReadingTextTranslation, ReadingWordGloss, Profile
from server.enums import TextUnit
from server.auth.models import Account
from server.auth.models import Base as AuthBase
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from server.db import Base

@pytest.fixture
def db_session():
    # Setup in-memory SQLite db
    engine = create_engine("sqlite:///:memory:", echo=False)
    Base.metadata.create_all(bind=engine)
    AuthBase.metadata.create_all(bind=engine)
    TestingSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
    session = TestingSessionLocal()
    try:
        yield session
    finally:
        session.close()

# Sample data mocking LLM outputs
SAMPLE_TEXT_RESPONSE = """
{
  "title": "The Cat",
  "text": "The cat sat on the mat."
}
"""

SAMPLE_WORD_RESPONSE = """
{
  "words": [
    {
      "word": "cat",
      "lemma": "cat",
      "pos": "noun",
      "translation": "gato",
      "lemma_translation": "gato"
    },
    {
      "word": "mat",
      "lemma": "mat",
      "pos": "noun",
      "translation": "alfombra",
      "lemma_translation": "alfombra"
    }
  ]
}
"""

SAMPLE_SENTENCE_RESPONSE = """
{
  "target_lang": "es",
  "paragraphs": [
    {
      "sentences": [
        {
          "text": "The cat sat on the mat.",
          "translation": "El gato se sentó en la alfombra."
        }
      ]
    }
  ]
}
"""

SAMPLE_TITLE_RESPONSE = """
{
  "translation": "El Gato"
}
"""

@pytest.fixture
def test_user(db_session):
    # Create a test account and profile
    account = Account(id=999, email="pipeline_test@example.com", password_hash="hash", subscription_tier="Free")
    db_session.add(account)
    db_session.flush()
    
    profile = Profile(account_id=999, lang="es", target_lang="en")
    db_session.add(profile)
    db_session.commit()
    return account

def test_text_generation_persistence(db_session, test_user):
    """Test that text generated by LLM is correctly persisted to DB."""
    service = TextGenerationService()
    account_id = test_user.id
    lang = "es"
    target_lang = "en"
    
    # 1. Create placeholder in global DB (same session in test)
    text_id = service.create_placeholder_text(
        db_session, account_id, lang, target_lang=target_lang
    )
    assert text_id is not None

    # 2. Generate Content (Mocked)
    with patch("server.services.text_generation_service.llm_call_and_log_to_file") as mock_llm:
        mock_llm.return_value = (SAMPLE_TEXT_RESPONSE, {}, "mock-provider", "mock-model")
        
        mock_dir = MagicMock()
        mock_dir.__truediv__.return_value = MagicMock()

        # account_db and global_db are same in test
        result = service.generate_text_content(
            db_session, db_session, account_id, lang, text_id, 
            job_dir=mock_dir, messages=[]
        )
        
    assert result.success
    assert result.text == "The cat sat on the mat." 
    assert result.title == "The Cat"
    
    # 3. Verify DB
    rt = db_session.query(ReadingText).filter_by(id=text_id).first()
    assert rt is not None
    assert rt.content == "The cat sat on the mat."
    assert rt.generated_at is not None
    assert rt.target_lang == "en"

def test_word_translation_persistence(db_session, test_user):
    """Test that word translations are correctly persisted to global DB."""
    # Setup existing text (global model - no account_id)
    rt = ReadingText(lang="es", target_lang="en", content="The cat sat on the mat.")
    db_session.add(rt)
    db_session.commit()
    
    service = TranslationService()
    
    with patch("server.services.translation_service.llm_call_and_log_to_file") as mock_llm:
        mock_llm.return_value = (SAMPLE_WORD_RESPONSE, {}, "mock-provider", "mock-model")
        
        dummy_reading_msgs = [
            {"role": "system", "content": "system prompt"},
            {"role": "user", "content": "user prompt"}
        ]

        # Method now takes global_db (db), no account_id needed for inserts
        success = service._generate_word_translations(
            db_session, test_user.id, rt.id, "es", "en", rt.content, 
            job_dir=MagicMock(), provider="mock", model_id="mock", base_url="mock",
            w_messages=[], reading_messages=dummy_reading_msgs, full_response=rt.content
        )
        
    assert success
    
    # Verify DB - now filtering by text_id and target_lang
    words = db_session.query(ReadingWordGloss).filter_by(
        text_id=rt.id, target_lang="en"
    ).all()
    
    assert len(words) >= 2
    
    cat = next((w for w in words if w.surface == "cat"), None)
    assert cat is not None
    assert cat.translation == "gato"
    assert cat.pos == "noun"
    
    mat = next((w for w in words if w.surface == "mat"), None)
    assert mat is not None
    assert mat.translation == "alfombra"

def test_sentence_translation_persistence(db_session, test_user):
    """Test that sentence translations are correctly persisted to global DB."""
    # Setup existing text (global model)
    rt = ReadingText(lang="es", target_lang="en", content="The cat sat on the mat.")
    db_session.add(rt)
    db_session.commit()
    
    service = TranslationService()
    
    with patch("server.services.translation_service.llm_call_and_log_to_file") as mock_llm:
        mock_llm.return_value = (SAMPLE_SENTENCE_RESPONSE, {}, "mock-provider", "mock-model")
        
        # Method now takes global_db
        success = service._generate_sentence_translations(
            db_session, test_user.id, rt.id, "es", "en", rt.content,
            job_dir=MagicMock(), provider="mock", model_id="mock", base_url="mock",
            tr_messages=[]
        )

    assert success
    
    # Verify DB - now filtering by text_id and target_lang
    sents = db_session.query(ReadingTextTranslation).filter_by(
        text_id=rt.id, target_lang="en", unit=TextUnit.SENTENCE
    ).all()
    assert len(sents) == 1
    assert sents[0].source_text == "The cat sat on the mat."
    assert sents[0].translated_text == "El gato se sentó en la alfombra."
    assert sents[0].span_start == 0
    assert sents[0].span_end == len("The cat sat on the mat.")

def test_title_translation_persistence(db_session, test_user):
    """Test that title translation is correctly persisted to global DB."""
    rt = ReadingText(lang="es", target_lang="en", content="Content")
    db_session.add(rt)
    db_session.commit()
    
    service = TranslationService()
    
    with patch("server.services.translation_service.llm_call_and_log_to_file") as mock_llm:
        mock_llm.return_value = (SAMPLE_TITLE_RESPONSE, {}, "mock-provider", "mock-model")
        
        # Method now takes global_db
        success = service._generate_title_translation(
            db_session, test_user.id, rt.id, "es", "en", "The Cat",
            job_dir=MagicMock(), provider="mock", model_id="mock", base_url="mock"
        )
        
    assert success
    
    # Verify DB - now filtering by text_id and target_lang
    title = db_session.query(ReadingTextTranslation).filter_by(
        text_id=rt.id, target_lang="en", unit=TextUnit.TEXT
    ).first()
    assert title is not None
    assert title.source_text == "The Cat"
    assert title.translated_text == "El Gato"
